default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('PG_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('PG_PASSWORD', '') %>
  host: <%= ENV.fetch('PG_HOST', 'localhost') %>

development:
  <<: *default
  database: atelier_lapieuvre_development

# The test database is used by the test suite and recreated between runs.
test:
  <<: *default
  database: atelier_lapieuvre_test

production:
  <<: *default
  # In production, prefer using DATABASE_URL provided by Heroku or your hosting provider.
  url: <%= ENV['DATABASE_URL'] %>
